# ARM Build Failure Marker
# This file indicates that ARM builds are disabled for this module
# Remove this file to re-enable ARM builds

reason: Testing ARM failure filtering
date: '2025-06-02'
reported_by: test-user
