name: "parabricks_fq2bam"
description: NVIDIA Clara Parabricks GPU-accelerated alignment, sorting, BQSR calculation,
  and duplicate marking. Note this nf-core module requires files to be copied into
  the working directory and not symlinked.
keywords:
  - align
  - sort
  - bqsr
  - duplicates
tools:
  - "parabricks":
      description: "NVIDIA Clara Parabricks GPU-accelerated genomics tools"
      homepage: "https://www.nvidia.com/en-us/clara/genomics/"
      documentation: "https://docs.nvidia.com/clara/parabricks/4.0.1/Documentation/"
      licence: ["custom"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - read_group:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - r1_fastq:
        type: file
        description: R1 fastq file
        pattern: "*.fastq.gz"
    - r2_fastq:
        type: file
        description: R2 fastq file
        pattern: "*.fastq.gz"
    - interval_file:
        type: file
        description: file or files containing genomic intervals for use in base quality
          score recalibration.
        pattern: "*.{bed,interval_list,picard,list,intervals}"
  - - fasta:
        type: file
        description: reference fasta file - must be unzipped
        pattern: "*.{fasta,fa}"
    - fai:
        type: file
        description: reference fasta fai index
        pattern: "*.fai"
  - - meta1:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - index:
        type: file
        description: reference BWA index
        pattern: "*.{amb,ann,bwt,pac,sa}"
  - - known_sites:
        type: file
        description: (optional) known sites file(s) for calculating BQSR. markdups must
          be true to perform BQSR.
        pattern: "*.vcf.gz"
output:
  - bam_bai:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test']
      - "*.bam":
          type: file
          description: output bam file
          pattern: "*.bam"
      - "*.bai":
          type: file
          description: output bam bai file
          pattern: "*.bai"
  - qc_metrics:
      - meta:
          type: map
          description: (optional) optional directory of qc metrics
      - qc_metrics/*:
          type: directory
          description: (optional) optional directory of qc metrics
          pattern: "qc_metrics"
  - bqsr_table:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test']
      - "*.table":
          type: file
          description: bqsr table
          pattern: "*.table"
  - duplicate_metrics:
      - meta:
          type: map
          description: (optional) metrics calculated from marking duplicates in the bam
      - "*.duplicate-metrics.txt":
          type: file
          description: (optional) metrics calculated from marking duplicates in the bam
          pattern: "*-duplicate-metrics.txt"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions.
          pattern: "versions.yml"
authors:
  - "@bsiranosian"
  - "@adamrtalbot"
maintainers:
  - "@bsiranosian"
  - "@adamrtalbot"
  - "@gallvp"
  - "@famosab"
