---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - openjdk=11.0
  - perl=5.32.1
  - procps-ng=4.0.4
  - python=3.13.2
  - wget=1.21.4
