---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::blast=2.2.31
  - bioconda::salmon=0.6.0
  - bioconda::snap-aligner=1.0dev.96
  - bioconda::transrate=1.0.3
