name: Wave
# When environment.yml is changed
on:
  pull_request:
    paths:
      - "**/environment.yml"
      - "**/Dockerfile"

# TODO On complete call testing CI
# TODO Skip testing CI if any changes to environment.yml

env:
  # renovate: datasource=github-releases depName=seqeralabs/wave-cli versioning=semver
  WAVE_VERSION: "1.5.0"
  # renovate: datasource=github-releases depName=askimed/nf-test versioning=semver
  NFT_VER: "0.9.2"
  # renovate: datasource=github-releases depName=nextflow/nextflow versioning=semver
  NXF_VER: "24.10.1"

jobs:
  generate-matrix:
    name: generate-matrix
    runs-on: ubuntu-latest
    # Only run on Pull Requests within the same repository, and not from forks
    if: github.event.pull_request.head.repo.full_name == github.repository
    outputs:
      conda-matrix: ${{ steps.conda-diff.outputs.all_changed_files }}
      dockerfile-matrix: ${{ steps.docker-diff.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Find conda differences
        id: conda-diff
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          json: true
          escape_json: false
          files: |
            modules/**/environment.yml

      - name: Find Dockerfile differences
        id: docker-diff
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          json: true
          escape_json: false
          files: |
            modules/**/Dockerfile

  conda-wave:
    # NOTE This should get skipped because generate-matrix won't run
    # if: github.repository == 'nf-core/modules'
    if: ${{ needs.generate-matrix.outputs.conda-matrix != '[]' }}
    needs: generate-matrix
    name: Build ${{ matrix.profile }} ${{ matrix.platform }} Container
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        files: "${{ fromJson(needs.generate-matrix.outputs.conda-matrix) }}"
        profile: [docker, singularity]
        platform: ["linux/amd64", "linux/arm64"]
    outputs:
      container_info: ${{ steps.build_container.outputs.container_output }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install wave-cli
        run: |
          wget -q https://github.com/seqeralabs/wave-cli/releases/download/v${WAVE_VERSION}/wave-${WAVE_VERSION}-linux-x86_64
          sudo mv wave-${WAVE_VERSION}-linux-x86_64 /usr/local/bin/wave
          chmod +x /usr/local/bin/wave

      - name: Build ${{ matrix.profile }} container
        id: build_container
        # FIXME Hack while iron out the CI
        continue-on-error: true
        env:
          PROFILE: ${{ (contains(matrix.profile, 'singularity') && '--singularity') || '' }}
        run: |
          output=$(wave --conda-file "${{ matrix.files }}" \
              $PROFILE \
              --freeze \
              --await \
              --platform ${{ matrix.platform }} \
              --tower-token ${{ secrets.TOWER_ACCESS_TOKEN }} \
              --tower-workspace-id ${{ secrets.TOWER_WORKSPACE_ID }})
          echo "container_output=$output" >> $GITHUB_OUTPUT

  dockerfile-wave:
    # NOTE This should get skipped because generate-matrix won't run
    # if: github.repository == 'nf-core/modules'
    if: ${{ needs.generate-matrix.outputs.dockerfile-matrix != '[]' }}
    needs: generate-matrix
    name: Build Dockerfile-based ${{ matrix.platform }} Container
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        files: "${{ fromJson(needs.generate-matrix.outputs.dockerfile-matrix) }}"
        # NOTE singularity build requires a Singularity definition file in place of Dockerfile
        # https://nextflow.slack.com/archives/C0477AS31T5/p1731755350230149?thread_ts=1731697852.661849&cid=C0477AS31T5
        # profile: [docker]
        platform: ["linux/amd64", "linux/arm64"]
    outputs:
      container_info: ${{ steps.build_container.outputs.container_output }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install wave-cli
        run: |
          wget -q https://github.com/seqeralabs/wave-cli/releases/download/v${WAVE_VERSION}/wave-${WAVE_VERSION}-linux-x86_64
          sudo mv wave-${WAVE_VERSION}-linux-x86_64 /usr/local/bin/wave
          chmod +x /usr/local/bin/wave

      - name: Create a registry name
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        id: registry-name
        with:
          result-encoding: string
          script: |
            return '${{ matrix.files }}'.replace('modules/nf-core/', '').replace('/Dockerfile', '').replace('/', '_');

      - name: Build ${{ matrix.platform }} container
        id: build_container
        # NOTE If you're changing a Dockerfile and this is running, try to update the Dockerfile to build with wave
        continue-on-error: false
        run: |
          output=$(wave -f "${{ matrix.files }}" \
              --freeze \
              --await \
              --platform ${{ matrix.platform }} \
              --build-repo quay.io/nf-core/modules/${{steps.registry-name.outputs.result}} \
              --cache-repository quay.io/nf-core/wave-cache/docker/${{ matrix.platform }} \
              --tower-token ${{ secrets.TOWER_ACCESS_TOKEN }} \
              --tower-workspace-id ${{ secrets.TOWER_WORKSPACE_ID }})
          echo "container_output=$output" >> $GITHUB_OUTPUT

  update-meta-yml:
    needs: [generate-matrix, conda-wave, dockerfile-wave]
    if: ${{ needs.generate-matrix.outputs.conda-matrix != '[]' || needs.generate-matrix.outputs.dockerfile-matrix != '[]' }}
    name: Update meta.yml with Container Info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Update meta.yml files
        run: |
          python .github/scripts/update_meta_yml.py \
            --conda-files '${{ needs.generate-matrix.outputs.conda-matrix }}' \
            --dockerfile-files '${{ needs.generate-matrix.outputs.dockerfile-matrix }}' \
            --conda-containers '${{ needs.conda-wave.outputs.container_info }}' \
            --dockerfile-containers '${{ needs.dockerfile-wave.outputs.container_info }}'

      - name: Commit changes
        run: |
          git config user.email "infrastructure@nf-co.re"
          git config user.name "nf-core-bot"
          git add "**/meta.yml"
          git diff --staged --quiet || git commit -m "[automated] Update container info in meta.yml [skip ci]"
          git push
